# Generated by Django 5.0.4 on 2024-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('rating', models.IntegerField()),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='books')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='authors')),
                ('books', models.ManyToManyField(to='books.book')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
